### ISSUE TITLE
Convenience task for cloning all plugin repositories

### ISSUE THREAD

**Issue by rmc3** [sensu-plugins/GIR#14]
It might be convenient to have a task that clones or updates all plugin repositories. On first setting up my GIR environment, I ended up running the following for loop, which was rather ugly.

```
for i in $(rake github:list_repos | awk '{print $2}'); do rake git:clone plugin=$i; done
```

Something a bit prettier would be much appreciated!

**Comment by mattyjones** [comment]
@rmc3 I have several thoughts on that matter
1. I really hadn't intended for someone to clone everything, but that is just me.  I was more thinking someone would clone a few.  I will add a flag `all` that does this.
2. One thing bugging me is that I only take in a string, I intend on setting this to an array that way I can do multiple repos at once.  Just haven't found the time yet.
3. Going overboard here but I was also toying with the idea of using a ruby regex to define the repo with it matching against either the description or the name. (this would be a pia so I am not sure I will ever get around to it, but it would be cool)
