### ISSUE TITLE
Gem v Rake

### ISSUE THREAD

**Issue by mattyjones** [sensu-plugins/GIR#25]
@sensu-plugins/contributors 

Thoughts on making this a gem instead of a shit ton of rake tasks.  I have been toying with the idea ever since it became more than 1/2 dozen tasks.

Pros:
- Using it would be easier as all tasks would be binaries
- Could combine some tasks and just pass flag (clone --all vs X )
- More seamless integration
- Easier development and management once the initial conversion is done
- Could be more useful to people on other projects orgs by abstracting out the sensu bits to a json config file

Cons:
- A lot of work for a pet project
- A lot of binaries to remember vs `Rake -T`
- Something else to install on a system
- Wishful thinking

**Comment by analytically** [comment]
My vote goes to leaving it as rake tasks. Mainly because of Cons #1 and #4.
